cbv/cbv/basic_app/urls.py
from django.urls import path,re_path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name='list'),
    path('create/',views.SchoolCreateView.as_view(),name='create'),
    path('<pk>/',views.SchoolDetailView.as_view(),name='detail'),
    path('<pk>/update/',views.SchoolUpdateView.as_view(),name='update'),
    path('<pk>/delete/',views.SchoolDeleteView.as_view(),name='update'),
]
# re_path is used to check for regex in path

cbv/cbv/cbv/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view()),
    path('basic_app/',include('basic_app.urls'),name='basic_app')
]

cbv/cbv/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs={'pk':self.pk})

class Student(models.Model):
    name =models.CharField(max_length=256)
    age= models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students',on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

cbv/cbv/basic_app/views.py
from django.shortcuts import render
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView,UpdateView,
                                DeleteView)
from basic_app import models
from django.urls import reverse_lazy
# from django.http import HttpResponse

# Create your views here.

#function based
# def index(request):
#     return render(request,'index.html')

#class based
# class CBView(View):
#     def get(self,request):
#         return HttpResponse("Class Based Views are Cool")

class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = 'Basic Injection'
        return context

class SchoolListView(ListView):
    context_object_name = 'schools' #defining our own context name
    model = models.School
    # school_list will be returned it iis default context name
    template_name = 'basic_app/school_list.html'

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School 
    template_name = 'basic_app/school_detail.html'


class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy('basic_app:list')

cbv/cbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="#"></a></li>
        </ul>
    </nav>
    <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>
</body>
</html>

cbv/cbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<h1>Delete {{school.name}}? </h1>
<form method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
</form>

{% endblock %}

cbv/cbv/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<div class="jumbotron">
    <h1>Welcome to school detail page</h1>
    <h2>School Details:</h2>
    <p>Name: {{ school_detail.name }}</p>
    <p>Principal: {{ school_detail.principal }}</p>
    <p>Location: {{ school_detail.location }}</p>
    <h3>Students</h3>

    {% for student in school_detail.students.all %}
    <p>{{student.name}} who is {{student.age}} years old</p>
    {% endfor %}

</div>

<div class="container">
    <p><a class='btn btn-warning' href=" {% url 'basic_app:update' pk=school_detail.pk %} " >Update</a></p>
</div>

{% endblock %}

cbv/cbv/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<h1>
    {% if not form.instance.pk %}
    Create School
    {% else %}
    Update School
    {% endif %}
</h1>

<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-primary" value='Submit'>

</form>

{% endblock %}

cbv/cbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<h1>List of Schools</h1>

<ol>
    {% for school in schools %}
    <h2><li><a href='{{school.id}}' >{{ school.name }}</a></li></h2>
    {% endfor %}
</ol>

{% endblock %}

cbv/cbv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="#"></a></li>
        </ul>
    </nav>

    <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>
    
</body>
</html>

cbv/cbv/templates/index.html
{% extends 'base.html' %}

{% block body_block %}
    <div class="jumbotron">
        <h1>Home Page!</h1>
    </div>
{% endblock %}